import json
OUT="/tmp/claude-0/-home-claude-tullamarine-flight-map/a94e428b-9c1e-5182-90c8-c6aeb42cd856/scratchpad/regions/small_infra.json"
market_url="https://discover.cotality.com/hubfs/Article-Reports/COTALITY%20HVI%20SEP%202026%20FINAL%20(1).pdf"

tas={
 "city":"Hobart","stateName":"Tasmania","abbr":"TAS",
 "mainAirport":{"icao":"YMHB","name":"Hobart International Airport","short":"Hobart Airport",
  "lng":147.5103,"lat":-42.8362,
  "runways":[{"refs":["12","30"],"ends":[[147.5020,-42.8290],[147.5247,-42.8455]],
    "plain":"main (only) runway, north-west to south-east","era":"both","opens":None}],
  "wideBodies":False,
  "curfew":"No curfew (24-hour airport)",
  "noiseUrl":"https://aircraftnoise.airservicesaustralia.com/2020/11/06/hobart-flight-paths/",
  "notes":"Single runway 12/30, 2,727 m (extended 2017-18; strengthened/widened for A350/787 in 2024-25, reopened Aug 2025). Traffic is mostly A320/737 and turboprops; no regular wide-body services yet (Air New Zealand to Auckland uses narrow-bodies; Antarctic and freight flights occasional). Runway-end coordinates are from SkyVector (0.01-minute precision, ~20 m); the runway 12 end has a ~120 m displaced threshold, so ends[0] is the physical runway end, slightly north-west of the landing threshold. Flight path changes in 2022 drew complaints (Aircraft Noise Ombudsman investigation) in suburbs such as Seven Mile Beach, Lewisham and the eastern shore."},
 "otherAirports":[
  {"icao":"YCBG","name":"Cambridge Aerodrome","lng":147.4747,"lat":-42.8267,"kind":"light","status":"open","opens":None,
   "runways":[
    {"refs":["12","30"],"ends":[[147.4700,-42.8232],[147.4794,-42.8302]],"plain":"main runway (approximate position)","era":"both","opens":None},
    {"refs":["09","27"],"ends":[[147.4688,-42.8255],[147.4806,-42.8278]],"plain":"cross runway (approximate position)","era":"both","opens":None}],
   "note":"Small general-aviation field about 3 km west of Hobart Airport: Par Avion scenic flights, the aero club's training aircraft and helicopters. Put up for sale in June 2024; homes in Cambridge and Seven Mile Beach hear light aircraft and helicopters. Runway ends are APPROXIMATE (placed from the reference point, runway length ~1,100-1,200 m and magnetic headings plus ~15.5 deg variation), not surveyed."}],
 "future":None,
 "plans":[
  {"kind":"rail","name":"Northern Suburbs Rapid Bus (Northern Suburbs Transit Corridor)","status":"Planning; public consultation closes 9 Oct 2026, no build date yet",
   "about":"Rapid bus between the city and Claremont every 10 min at peak, partly on the unused northern rail corridor, with 12 stops including New Town, Moonah, Glenorchy and Berriedale. Light rail options have faded in favour of bus rapid transit.",
   "url":"https://www.transport.tas.gov.au/roadworks/road_improvement_plans/northern_suburbs_transit_corridor",
   "cert":"approx",
   "line":[[147.3330,-42.8800],[147.3230,-42.8700],[147.3080,-42.8580],[147.2990,-42.8470],[147.2900,-42.8380],[147.2760,-42.8320],[147.2660,-42.8250],[147.2600,-42.8160],[147.2530,-42.7880]]},
  {"kind":"road","name":"New Bridgewater Bridge","status":"Opened June 2025",
   "about":"$786m four-lane bridge over the Derwent between Granton and Bridgewater replacing the 1946 lift bridge, part of the Midland Highway. Faster trips from Brighton/Bridgewater into Hobart.",
   "url":"https://www.bridgewaterbridge.tas.gov.au/",
   "cert":"approx",
   "line":[[147.2200,-42.7420],[147.2260,-42.7390],[147.2320,-42.7365],[147.2380,-42.7345],[147.2440,-42.7320]]},
  {"kind":"road","name":"Southern Outlet transit lane (fifth lane)","status":"Partly built; Davey-Macquarie connector done, main lane unfunded/undated (costs up to $95m, 2026)",
   "about":"A fifth, bus/transit lane on the Southern Outlet between Tolmans Hill and the city to ease Kingston commuter congestion. The southern section to Kingston is not yet designed.",
   "url":"https://www.transport.tas.gov.au/roadworks/current_projects/south_road_projects/southern_outlet_transit_lane",
   "cert":"approx",
   "line":[[147.3215,-42.8880],[147.3165,-42.8930],[147.3110,-42.8990],[147.3085,-42.9040],[147.3070,-42.9110]]},
  {"kind":"road","name":"Tasman Highway: Midway Point and Sorell causeways duplication","status":"Design and environmental approvals (2026); no construction date",
   "about":"$187m to widen the causeways between Hobart Airport and Sorell to four lanes, add a second McGees Bridge and raise the road for flooding. Part of the $350m South East Traffic Solution.",
   "url":"https://www.transport.tas.gov.au/roadworks/current_projects/south_road_projects/south_east_traffic_solution/tasman_highway_between_airport_and_sorell",
   "cert":"approx",
   "line":[[147.5060,-42.8110],[147.5180,-42.8050],[147.5300,-42.7995],[147.5410,-42.7960],[147.5520,-42.7910],[147.5620,-42.7860]]}
 ],
 "railHubs":[
  [147.3350,-42.8790,"Macquarie Point","City end of the northern corridor; AFL stadium site (site works began Jul 2026)"],
  [147.2990,-42.8470,"Moonah","Proposed rapid bus stop"],
  [147.2760,-42.8320,"Glenorchy","Proposed rapid bus stop, main northern hub"],
  [147.2530,-42.7880,"Claremont","Proposed northern end of rapid bus"]],
 "dataCentres":[
  ["TasmaNet DC1","TasmaNet","Hobart TAS 7000","live","Exact street address not confirmed; suburb only"],
  ["DXN Tasmania One (DXN-TAS01, formerly TasmaNet DC3)","DXN","Hobart TAS 7000","live","Bought from TasmaNet in 2020; exact street address not confirmed; suburb only"]],
 "market":{"text":"Hobart home values fell 0.2% in August 2026, were down 0.2% over three months but up 8.1% over the year, and sit 1.1% below the March 2022 peak (Cotality).","url":market_url,"month":"2026-08"},
 "tallBuilding":"Wrest Point hotel tower is about 73 m (approximate)",
 "defaultHome":{"title":"Kingston","lng":147.3048,"lat":-42.9765},
 "schoolZoneUrl":"https://www.decyp.tas.gov.au/learning/find-your-local-school/intake-areas-tasmanian-government-schools/",
 "view":{"center":[147.40,-42.86],"zoom":10.3,"bearing":0},
 "links":[
  ["SkyVector YMHB","https://skyvector.com/airport/YMHB/Hobart-Airport"],
  ["Hobart Airport (Wikipedia)","https://en.wikipedia.org/wiki/Hobart_Airport"],
  ["Airservices: Hobart flight paths","https://aircraftnoise.airservicesaustralia.com/2020/11/06/hobart-flight-paths/"],
  ["Airservices: Hobart noise abatement","https://aircraftnoise.airservicesaustralia.com/2025/05/30/hobart-airport-noise-abatement-procedure-overview/"],
  ["Cambridge Aerodrome (Wikipedia)","https://en.wikipedia.org/wiki/Cambridge_Aerodrome"],
  ["Northern Suburbs Rapid Bus consultation","https://www.premier.tas.gov.au/latest-news/2026/september/have-your-say-on-the-northern-suburbs-rapid-bus-project"],
  ["Midway Point and Sorell causeways","https://www.transport.tas.gov.au/roadworks/current_projects/south_road_projects/south_east_traffic_solution/tasman_highway_between_airport_and_sorell"],
  ["Southern Outlet cost update (ABC, Jun 2026)","https://www.abc.net.au/news/2026-06-23/further-cost-blow-out-southern-outlet-widening-project-hobart/106824890"],
  ["Macquarie Point stadium site works","https://www.premier.tas.gov.au/latest-news/2026/july/site-preparations-begin-for-macquarie-point-multipurpose-stadium"],
  ["Cotality HVI (Sep 2026 release)",market_url]]
}

act={
 "city":"Canberra","stateName":"Australian Capital Territory","abbr":"ACT",
 "mainAirport":{"icao":"YSCB","name":"Canberra Airport","short":"Canberra Airport",
  "lng":149.1950,"lat":-35.3070,
  "runways":[
   {"refs":["17","35"],"ends":[[149.1945,-35.2907],[149.1945,-35.3148]],"plain":"main north-south runway","era":"both","opens":None},
   {"refs":["12","30"],"ends":[[149.1852,-35.3007],[149.1988,-35.3100]],"plain":"shorter cross runway","era":"both","opens":None}],
  "wideBodies":False,
  "curfew":"No curfew (24/7); noise abatement areas keep jets at 5,000 ft+ over most suburbs",
  "noiseUrl":"https://www.canberraairport.com.au/corporate/community/aircraft-noise",
  "notes":"Main runway 17/35 is 2,983 m; 12/30 is 1,679 m. Mostly A320/737/E190 domestic jets plus turboprops and RAAF VIP/defence aircraft (Fairbairn); international is narrow-body (e.g. Bali, Fiji) with no regular wide-body passenger service. Since 1996 noise abatement areas require jets to stay at least 5,000 ft (others 3,000 ft) above most of Canberra, which the airport says protects 99.5% of houses from direct overflight; traffic funnels over the Majura valley, Queanbeyan/Jerrabomberra and Hume/Tuggeranong-east. Airport says night freight and international flying will grow. Coordinates from SkyVector (0.01-minute precision); runway 35 has a ~300 m displaced threshold and 30 a ~65 m one, so those ends are physical runway ends. Airservices WebTrak shows live tracks."},
 "otherAirports":[],
 "future":None,
 "plans":[
  {"kind":"rail","name":"Light Rail Stage 2A: City to Commonwealth Park","status":"Under construction; works finish early 2027, passengers early 2028",
   "about":"1.7 km extension from Alinga Street around London Circuit to Commonwealth Park with new stops at Edinburgh Avenue, City South and Commonwealth Park.",
   "url":"https://www.act.gov.au/lightrailtowoden/stage-2a","cert":"approx",
   "line":[[149.1314,-35.2784],[149.1290,-35.2790],[149.1262,-35.2808],[149.1258,-35.2830],[149.1275,-35.2848],[149.1288,-35.2880]]},
  {"kind":"rail","name":"Light Rail Stage 2B: Commonwealth Park to Woden","status":"Awaiting environmental approval (decision expected end 2026); construction around 2030",
   "about":"Continues over Lake Burley Griffin on Commonwealth Avenue, around State Circle (east side) and along Adelaide Avenue to Woden, with 9 new stops.",
   "url":"https://www.act.gov.au/builtforcbr/browse-all-projects/transport/light-rail-to-woden","cert":"approx",
   "line":[[149.1288,-35.2880],[149.1275,-35.2935],[149.1290,-35.2990],[149.1330,-35.3050],[149.1290,-35.3110],[149.1200,-35.3140],[149.1080,-35.3170],[149.0950,-35.3310],[149.0870,-35.3450]]},
  {"kind":"rail","name":"Light Rail Stage 3 (Belconnen - City - Airport)","status":"Concept only; no funding or date",
   "about":"Future east-west line long flagged by the ACT Government linking Belconnen, the City, Russell and the Airport.",
   "url":"https://www.act.gov.au/lightrailtowoden","cert":"concept",
   "line":[[149.0660,-35.2390],[149.1000,-35.2600],[149.1314,-35.2784],[149.1500,-35.2980],[149.1900,-35.3070]]},
  {"kind":"road","name":"Monaro Highway upgrade (Lanyon Drive interchange, Hume)","status":"Under construction; this stage done end 2026",
   "about":"New flyover/interchange at Lanyon Drive and a duplicated Dog Trap Creek bridge on the Monaro Highway through Hume.",
   "url":"https://www.act.gov.au/our-canberra/latest-news/2026/march/upgrades-on-major-canberra-roads-continue","cert":"approx",
   "line":[[149.1720,-35.3650],[149.1700,-35.3760],[149.1680,-35.3860],[149.1660,-35.3960]]},
  {"kind":"road","name":"Athllon Drive duplication (Sulwood Dr to Drakeford Dr)","status":"Approved; main construction to start late 2026",
   "about":"Duplicates 2.4 km of Athllon Drive in Tuggeranong between Sulwood Drive and Drakeford Drive.",
   "url":"https://www.act.gov.au/our-canberra/latest-news/2026/march/upgrades-on-major-canberra-roads-continue","cert":"approx",
   "line":[[149.0880,-35.3860],[149.0850,-35.3940],[149.0810,-35.4020]]},
  {"kind":"road","name":"William Hovell Drive duplication","status":"Early works; main construction starting 2026",
   "about":"Duplicates 4.5 km of William Hovell Drive between Drake-Brockman Drive (Belconnen) and John Gorton Drive (Molonglo).",
   "url":"https://www.act.gov.au/builtforcbr/browse-all-projects/transport/william-hovell-drive-duplication","cert":"concept",
   "line":[[149.0310,-35.2420],[149.0400,-35.2520],[149.0480,-35.2600]]}
 ],
 "railHubs":[
  [149.1314,-35.2784,"Alinga Street","Current light rail terminus; Stage 2A starts here"],
  [149.1275,-35.2848,"City South","New Stage 2A stop"],
  [149.1288,-35.2880,"Commonwealth Park","Stage 2A terminus (early 2028)"],
  [149.0870,-35.3450,"Woden","Planned Stage 2B terminus"],
  [149.1320,-35.1860,"Gungahlin Place","Existing light rail northern terminus"]],
 "dataCentres":[
  ["CDC Hume HU1","Canberra Data Centres (CDC)","54 Sheppard St, Hume ACT 2620","live",""],
  ["CDC Hume HU4","Canberra Data Centres (CDC)","7 Tralee St, Hume ACT 2620","live",""],
  ["CDC Hume HU5","Canberra Data Centres (CDC)","7 Tralee St, Hume ACT 2620","live","Status per datacentermap listing; not separately verified"],
  ["CDC Hume Campus Two","Canberra Data Centres (CDC)","Hume ACT 2620","live","~51 MW campus; exact street not confirmed"],
  ["CDC Fyshwick Campus (FY1 and others)","Canberra Data Centres (CDC)","Fyshwick ACT 2609","live","~45 MW campus; exact street not confirmed"],
  ["NEXTDC C1 Canberra","NEXTDC","19 Battye St, Bruce ACT 2617","live","~4.4 MW"],
  ["Equinix CA1","Equinix","51 Dacre St, Mitchell ACT 2911","live",""],
  ["ADC Mitchell","Australian Data Centres","Dacre St, Mitchell ACT 2911","live","~7 MW; street number not confirmed"],
  ["Macquarie IC4 Bunker (Canberra campus)","Macquarie Data Centres","Hume ACT 2620","live","Suburb not confirmed from official page (believed Hume)"],
  ["Telstra Deakin","Telstra","109 Kent St, Deakin ACT 2600","live",""]],
 "market":{"text":"Canberra home values fell 1.1% in August 2026, 2.8% over three months and 0.4% over the year, and sit 5.2% below the May 2022 peak (Cotality).","url":market_url,"month":"2026-08"},
 "tallBuilding":"Telstra Tower on Black Mountain is about 195 m",
 "defaultHome":{"title":"Page (Belconnen)","lng":149.0500,"lat":-35.2380},
 "schoolZoneUrl":"https://www.act.gov.au/education-and-training/find-a-school-and-enrol/find-a-school-in-your-priority-enrolment-area",
 "view":{"center":[149.12,-35.30],"zoom":10.4,"bearing":0},
 "links":[
  ["SkyVector YSCB","https://skyvector.com/airport/YSCB/Canberra-Airport"],
  ["Canberra Airport aircraft noise","https://www.canberraairport.com.au/corporate/community/aircraft-noise"],
  ["Canberra Airport noise calculator","https://www.canberraairport.com.au/corporate/community/aircraft-noise-calculator"],
  ["Light Rail to Woden","https://www.act.gov.au/builtforcbr/browse-all-projects/transport/light-rail-to-woden"],
  ["Stage 2A","https://www.act.gov.au/lightrailtowoden/stage-2a"],
  ["ACT road upgrades (Mar 2026)","https://www.act.gov.au/our-canberra/latest-news/2026/march/upgrades-on-major-canberra-roads-continue"],
  ["Cotality HVI (Sep 2026 release)",market_url]]
}

nt={
 "city":"Darwin","stateName":"Northern Territory","abbr":"NT",
 "mainAirport":{"icao":"YPDN","name":"Darwin International Airport / RAAF Base Darwin","short":"Darwin Airport",
  "lng":130.8767,"lat":-12.4147,
  "runways":[
   {"refs":["11","29"],"ends":[[130.8653,-12.4093],[130.8945,-12.4192]],"plain":"main runway (west-north-west to east-south-east)","era":"both","opens":None},
   {"refs":["18","36"],"ends":[[130.8707,-12.4088],[130.8707,-12.4227]],"plain":"short north-south cross runway","era":"both","opens":None}],
  "wideBodies":True,
  "curfew":"No curfew (24-hour joint civil/military airfield)",
  "noiseUrl":"https://www.defence.gov.au/sites/default/files/2023-09/RAAF%20Base%20Darwin%20and%20Darwin%20International%20Airport%202043%20ANEF.pdf",
  "notes":"Joint-user airport: civil flights share the runways with RAAF Base Darwin. Main runway 11/29 is 3,354 m; 18/36 is 1,524 m. Airline traffic is mostly 737/A320/A220/turboprops (few scheduled wide-bodies), but military heavies (KC-30A/A330, C-17, P-8, visiting US tankers and transports) are regular, and fighters (F-35A, F/A-18, visiting foreign jets during Exercise Pitch Black in odd years) are by far the loudest events. The airport sits in the middle of the northern suburbs, so Ludmilla, Coconut Grove, Nightcliff, Marrara, Jingili, Millner, Karama and Berrimah are close to the runway ends. Defence publishes the 2043 ANEF (Sep 2023) covering RAAF Base Darwin, Darwin Airport and Robertson Barracks (army helicopters). B-52 bomber facilities and rotations are at RAAF Base Tindal near Katherine, ~300 km away, not Darwin, though US force posture works (e.g. USAF mission planning centre, fuel and apron works) also affect Darwin. Coordinates from SkyVector (0.01-minute precision)."},
 "otherAirports":[],
 "future":{"label":"Defence and airline growth to 2043 (2043 ANEF)","short":"2043 noise forecast",
  "explain":"Defence's 2043 ANEF for RAAF Base Darwin and Darwin Airport models growing civil and military flying (including new fighter types and allied activity) out to 2043. Check a home against those forecast contours rather than today's noise, especially near the 11/29 runway ends."},
 "plans":[
  {"kind":"road","name":"Roystonea Avenue duplication (Palmerston)","status":"Under construction; due December 2026",
   "about":"Duplicates Roystonea Avenue from Terry Drive to Lambrick Avenue and upgrades the Buscall Avenue intersection to ease peak congestion in Palmerston.",
   "url":"https://dli.nt.gov.au/projects/roystonea-avenue-duplication","cert":"approx",
   "line":[[130.9840,-12.4930],[130.9850,-12.5000],[130.9860,-12.5080],[130.9870,-12.5150]]},
  {"kind":"road","name":"Tiger Brennan Drive (duplicated; Berrimah Road overpass)","status":"Duplication complete; $165m Berrimah Road overpass finished 2025",
   "about":"Main dual-carriageway from the CBD past Winnellie and Berrimah to Palmerston; the Berrimah Road intersection is now grade-separated. No further duplication is currently planned.",
   "url":"https://ancr.com.au/portfolio-item/tiger-brennan-drive-and-berrimah-road-overpass/","cert":"approx",
   "line":[[130.8455,-12.4615],[130.8600,-12.4540],[130.8800,-12.4460],[130.9030,-12.4480],[130.9250,-12.4640],[130.9450,-12.4780],[130.9650,-12.4870]]},
  {"kind":"site","name":"Darwin Ship Lift Facility (Northern Marine Complex, East Arm)","status":"Under construction; staged operations from 2027",
   "about":"$515m ship lift and marine maintenance precinct at East Arm serving Defence, Border Force and commercial vessels. Industrial site, not a transport line.",
   "url":"https://infrastructure.nt.gov.au/project/darwin-ship-lift-facility","cert":"approx",
   "line":[[130.8880,-12.5000]]},
  {"kind":"site","name":"Middle Arm Precinct","status":"Strategic environmental assessment; no construction date",
   "about":"Proposed gas, minerals-processing and renewables industrial precinct on the Middle Arm peninsula across the harbour from Palmerston. Controversial; still in assessment.",
   "url":"https://dli.nt.gov.au/projects/middle-arm-precinct","cert":"approx",
   "line":[[130.9050,-12.5800]]}
 ],
 "railHubs":[],
 "dataCentres":[
  ["NEXTDC D1 Darwin","NEXTDC","2 Harvey St, Darwin City NT 0800","live","Address from datacentermap listing (~1 MW, opened 2024); verify"],
  ["NEXTDC D2 Darwin","NEXTDC","2-6 Ryko Ct, Darwin City NT 0800","plan","In development (~6 MW)"],
  ["DXN SDC Darwin (Secure Data Centre)","DXN","27 Harvey St, Darwin City NT 0800","live",""],
  ["Area9 Darwin","Area9","Darwin NT","live","Exact address not confirmed; suburb only"]],
 "market":{"text":"Darwin home values rose 0.6% in August 2026, 0.9% over three months and 14.6% over the year, and are at a record high; it was the only capital without a quarterly fall (Cotality).","url":market_url,"month":"2026-08"},
 "tallBuilding":"Darwin's tallest towers are roughly 100 m (approximate)",
 "defaultHome":{"title":"Rosebery (Palmerston)","lng":130.9850,"lat":-12.5080},
 "schoolZoneUrl":"https://nt.gov.au/learning/primary-and-secondary-students/choose-a-school",
 "view":{"center":[130.90,-12.45],"zoom":10.8,"bearing":0},
 "links":[
  ["SkyVector YPDN","https://skyvector.com/airport/YPDN/Darwin-Airport"],
  ["Defence 2043 ANEF: RAAF Base Darwin and Darwin Airport","https://www.defence.gov.au/sites/default/files/2023-09/RAAF%20Base%20Darwin%20and%20Darwin%20International%20Airport%202043%20ANEF.pdf"],
  ["Defence noise monitoring and reporting","https://www.defence.gov.au/about/locations-property/aircraft-noise/noise-monitoring-reporting"],
  ["RAAF Base Darwin Aircraft Noise Management Plan","https://www.airforce.gov.au/sites/default/files/2025-10/250530-RAAF%20Base-Darwin-BANMP.pdf"],
  ["US Force Posture infrastructure","https://www.defence.gov.au/defence-activities/programs-initiatives/united-states-force-posture-initiatives/infrastructure-developments"],
  ["Roystonea Avenue duplication","https://dli.nt.gov.au/projects/roystonea-avenue-duplication"],
  ["Darwin Ship Lift (DCN, Apr 2026)","https://www.thedcn.com.au/news/darwin-ship-lift-facility-tracks-toward-2027-operations"],
  ["Cotality HVI (Sep 2026 release)",market_url]]
}
json.dump({"tas":tas,"act":act,"nt":nt},open(OUT,"w"),indent=1)
